### ISSUE TITLE
Update plugin author and add updater code

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/edd-add-to-cart-popup#4]
We should update the author, url and maybe implement our updater. At the moment on the EDD site the zip has to be manually packaged and uploaded. We could also switch to deliver it directly from GitHub

**Comment by ashleyfae** [comment]
Our updater is already there: https://github.com/easydigitaldownloads/edd-add-to-cart-popup/blob/develop/includes/Aventura/Edd/AddToCartPopup/Core/Plugin.php#L80

But yes, we should change the author https://github.com/easydigitaldownloads/edd-add-to-cart-popup/blob/develop/edd-add-to-cart-popup.php#L8
