### ISSUE TITLE
Error after clicking "Preview Popup" button

### ISSUE THREAD

**Issue by dimadin** [easydigitaldownloads/edd-add-to-cart-popup#5]
"Preview Popup" button is added to all screens under _Downloads_ > _Settings_ > _Extensions_. However, it works only on _Add to Cart Popup_ page. On other pages, there is a log in console caused by broken Ajax call. Call is broken because it generates PHP Fatal error:

> Uncaught TypeError: Argument 1 passed to `Aventura\Edd\AddToCartPopup\Core\Popup::generatePreview()` must be of the type `array`, `null` given, called in `/app/public/wp-content/plugins/edd-add-to-cart-popup/includes/Aventura/Edd/AddToCartPopup/Core/Popup.php` on line 119 and defined in `/app/public/wp-content/plugins/edd-add-to-cart-popup/includes/Aventura/Edd/AddToCartPopup/Core/Popup.php`:101

**Comment by ashleyfae** [comment]
To clarify, this is the button being added to all screens (I didn't see it at first):

![Screenshot from 2021-07-13 13-02-38](https://user-images.githubusercontent.com/6324272/125448343-8f37bf6f-7801-463f-9226-22a58451d7a6.png)

**Comment by ashleyfae** [comment]
We should add another check like this: https://github.com/easydigitaldownloads/edd-add-to-cart-popup/blob/develop/includes/Aventura/Edd/AddToCartPopup/Core/Popup.php#L148-L150 but for `section=acp` (right now just it checks `tab=extensions`)
